HTTP/1.0 503 Found
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
<head>
<title>The End of the Internet</title>
</head>
<body>
<h1>You've reached the End of the Internet</h1>
</body>
</html>